stages:
  - build
  - store
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker info

Buid image:
  image: docker:24.0.5
  stage: build
  services:
    - docker:24.0.5-dind
  script:
    - docker build -t $IMAGE_TAG .

Build compose:
  image: docker/compose:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker-compose -f compose.yaml up -d

Store image:
  image: docker:latest
  stage: store
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  only:
    - main

Deploy to dokku:
  image: ilyasemenov/gitlab-ci-git-push
  stage: deploy
  environment:
    name: production
    url: http://localhost:9644
  only:
    - main
  script:
    - git-push ssh://dokku@162.38.112.145:22/beepenmieux
