stages:
  - Build
  - Test
  - Store
  - Deploy
  - Documentation

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

Buid image:
  tags:
    - shell
  stage: Build
  script:
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG .
  cache:
    key: ${CI_PIPELINE_ID}
    paths:
      - node_modules/

Static Code Analysis:
  tags:
    - docker
  image: node:latest
  stage: Test
  script:
    - npm install
    - npm run lint-no-fix

Dependency Security Scan:
  stage: Test
  image: node:latest
  script:
    - npm install
    - npm audit


Store image:
  tags:
    - shell
  stage: Store
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag $IMAGE_TAG ${CI_REGISTRY_IMAGE}:latest
    - docker tag $IMAGE_TAG ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  only:
    - main

Deploy to Production:
  tags:
    - docker
  image: ilyasemenov/gitlab-ci-git-push
  stage: Deploy
  when: manual
  environment:
    name: production
    url: http://localhost:9644
  only:
    - main
  script:
    - git-push ssh://dokku@162.38.112.145:22/beepenmieux

# Documentation:
#   tags:
#     - docker
#   stage: deploy
#   image: node:latest
#   script:
#     - npm install
#     - npm run docs
#   artifacts:
#     paths:
#       - public/
#   only:
#     - main

pages:
  tags:
    - docker
  stage: Documentation
  image: node:latest
  script:
    - npm install
    - npm run docs
  artifacts:
    paths:
      - public
  only:
    - main
