apiVersion: v1
kind: Service
metadata:
  name: beepenmieux
  labels:
    project: beep
    app: beepenmieux
    role: backend
spec:
  selector:
    project: beep
    app: beepenmieux
    role: backend
  ports:
  - port: 8080
    targetPort: 9644
